---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/short_urls":
    post:
      summary: create short url
      tags:
      - ShortUrls
      parameters: []
      responses:
        '201':
          description: created
        '422':
          description: unprocessable entity
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                original_url:
                  type: string
              required:
              - original_url
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
